### ISSUE TITLE
Self-signed certificates not working with Minio

### ISSUE THREAD

**Issue by KALRONG** [k1nd0ne/VolWeb#11]
Hi,

Trying to make the docker-compose infraestructure work found out that using the documentation commands the self-signed certificates where giving errors on the connection towards Minio, the solution I found was to add the cert_check=False after line 61 on https://github.com/k1nd0ne/VolWeb/blob/main/cases/views.py

Didnt create a PR as I think it should be up to the dev to decide if this should be hardcoded or another option that the userrs could customize.

Sadly seems that while creating cases now is possible uploading evidences still doesn't work it gives an xhr error:

Cross origin requests blocked: Source politic doesnt allow the read of remote resources (sorry, is a rough translation)

Best regards

**Comment by k1nd0ne** [comment]
Hello, 
Thank you for your interest in the VolWeb project! 

The error you are facing seems to come from your webbrowser not trusting the self sign certificate. 
I guess you are accepting the risk in your web browser ? 

If so, navigate to https://fqdn-or-ipaddress-of-volweb:9000 and accept the risk there too. 

You should be good to go.

Best regards. 
Félix.

**Comment by KALRONG** [comment]
Sorry for the delay on my reply, yeah, it was solved after accepting the risk on the browser :S it will be nice to have a little warning for dummies like me hehe

**Comment by k1nd0ne** [comment]
Hello, thank you for following up on this.
I have updated the documentation with more details about this use case.

Best regards.
