### ISSUE TITLE
Can't create a new case

### ISSUE THREAD

**Issue by tcccorp** [k1nd0ne/VolWeb#13]
hello, 

I promise,  I followed every part of the installation guide. 

i try to create a new case.  

As requested, I fill every items as below 

![image](https://github.com/k1nd0ne/VolWeb/assets/23424205/9b0723a3-542b-4e31-bfa3-40403164fd43)

but after several seconds, there is this error 

![image](https://github.com/k1nd0ne/VolWeb/assets/23424205/e30fe00f-d3bb-4f40-924b-579cfce3b9ca)

i saw a similar trouble and solution was to change rights for  volwev/docker/cases but cases wasn't in docker.  so I copied this directory into docker but no changes

I try to create a new case directly on /admin but I need a case bucket ID but I don't know what it is ...

![image](https://github.com/k1nd0ne/VolWeb/assets/23424205/46bd6406-9a25-4a3c-93b5-f2f0eeee6f7f)

some logs 

volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:31 +0000] "GET /statistics/ HTTP/2.0" 200 218 "https://192.168.1.5/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:31 +0000] "GET /static/fontawesomefree/webfonts/fa-brands-400.woff2 HTTP/2.0" 200 109808 "https://192.168.1.5/static/fontawesomefree/css/brands.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:44506 - - [01/Apr/2024:19:51:36] "GET /cases/" 200 14038
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:36 +0000] "GET /cases/ HTTP/2.0" 200 14038 "https://192.168.1.5/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:36 +0000] "GET /static/cases/css/cases.css HTTP/2.0" 200 270 "https://192.168.1.5/cases/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:36 +0000] "GET /static/js/cases.js HTTP/2.0" 200 11266 "https://192.168.1.5/cases/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:44508 - - [01/Apr/2024:19:51:36] "GET /websocket-url/" 200 38
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:36 +0000] "GET /websocket-url/ HTTP/2.0" 200 38 "https://192.168.1.5/cases/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:44522 - - [01/Apr/2024:19:51:36] "WSCONNECTING /ws/cases/" - -
volweb-platform      | 172.19.0.6:44522 - - [01/Apr/2024:19:51:36] "WSCONNECT /ws/cases/" - -
volweb-platform      | 172.19.0.6:44538 - - [01/Apr/2024:19:51:36] "GET /api/cases/" 200 2
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:19:51:36 +0000] "GET /api/cases/ HTTP/2.0" 200 2 "https://192.168.1.5/cases/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 2024-04-01 19:51:48,337 WARNING  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(IsADirectoryError(21, 'Is a directory'))': /265555ec-76c4-4afa-bc6c-90e7d136a749
volweb-platform      | 2024-04-01 19:51:48,805 WARNING  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(IsADirectoryError(21, 'Is a directory'))': /265555ec-76c4-4afa-bc6c-90e7d136a749
volweb-platform      | 2024-04-01 19:51:49,635 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(IsADirectoryError(21, 'Is a directory'))': /265555ec-76c4-4afa-bc6c-90e7d136a749
volweb-platform      | 2024-04-01 19:51:51,335 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(IsADirectoryError(21, 'Is a directory'))': /265555ec-76c4-4afa-bc6c-90e7d136a749
volweb-platform      | 2024-04-01 19:51:54,547 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(IsADirectoryError(21, 'Is a directory'))': /265555ec-76c4-4afa-bc6c-90e7d136a749
volweb-platform      | 2024-04-01 19:51:54,554 ERROR    Internal Server Error: /api/cases/
volweb-platform      | 172.19.0.6:54658 - - [01/Apr/2024:19:51:54] "POST /api/cases/" 500 33

if I take uuid in the log ( 265555ec-76c4-4afa-bc6c-90e7d136a749 ) I'm able to create a case on /admin,  it works :)

but after that, I try to upload a dump file and there is an network error . 

![image](https://github.com/k1nd0ne/VolWeb/assets/23424205/0ca22e98-c6de-459c-91d2-83ad04078bf3)

logs 

volweb-platform      | 172.19.0.6:41298 - - [01/Apr/2024:20:01:21] "GET /api/cases/1/" 200 191
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:20:01:21 +0000] "GET /api/cases/1/ HTTP/2.0" 200 191 "https://192.168.1.5/evidences/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:41312 - - [01/Apr/2024:20:01:21] "GET /minio_secrets/" 200 109
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:20:01:21 +0000] "GET /minio_secrets/ HTTP/2.0" 200 109 "https://192.168.1.5/evidences/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:51766 - - [01/Apr/2024:20:03:52] "GET /api/cases/1/" 200 191
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:20:03:52 +0000] "GET /api/cases/1/ HTTP/2.0" 200 191 "https://192.168.1.5/evidences/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
volweb-platform      | 172.19.0.6:51782 - - [01/Apr/2024:20:03:52] "GET /minio_secrets/" 200 109
volweb_nginx         | 192.168.1.3 - - [01/Apr/2024:20:03:52 +0000] "GET /minio_secrets/ HTTP/2.0" 200 109 "https://192.168.1.5/evidences/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"

Hope you ll be able to help me :)

**Comment by k1nd0ne** [comment]
Hello @tcccorp, 
Thank you for your interest in the VolWeb project!

From what I am seeing you are have deployed VolWeb in production mode and the issue is about your certificates.

Could you please provide the following information so I can investigate and try to reproduce your issue:
- Your environment variables values (make sure to replace any secrets with dummy values)
- On what operating system are you deploying VolWeb ? 
- Are you using a self-signed certificate ? 

If you are using self-signed certificate and did not add it in your browser trusted CAs:
- Did you accept the risks at [https://192.168.1.5:9000](https://192.168.1.5:9000) ? (Or else no upload possible from the front-end as mentioned in #11)
- What is the value of the CN/FQDN you have entered when signing the certificate ?

Best regards.

**Comment by k1nd0ne** [comment]
Hello @tcccorp, 

Thank you a lot for your message, glad it is now solved. 
I'll try to handle more error messages in time to warn the user about this specific case.

We'll grab a beer for sure! 

Best regards.
