### ISSUE TITLE
Create Case : Recieve Error ('NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f62a5c760>)

### ISSUE THREAD

**Issue by DFIRTH24** [k1nd0ne/VolWeb#20]
Hi 
Thank You for Developing this Project 

After Successfully Installation I Receive This Error during create Case : 

volweb-platform      | 2024-06-20 07:36:07,237 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f62a5c760>: Failed to establish a new connection: [Errno 111] Connection refused')': /806e627c-6008-4993-8523-2f0cebc11247

Please Help me How can i Create Case Without this error

**Comment by k1nd0ne** [comment]
Hello @DFIRTH24 
Thank you for your interest in the VolWeb project.

Your issue seems to be similar with the issue #13. Please take a look at it. 


Your problem is likely due to a miss-configuration.

Best regards.

**Comment by k1nd0ne** [comment]
Closed since new release.
