### ISSUE TITLE
Timeliner problem

### ISSUE THREAD

**Issue by Idodo6** [k1nd0ne/VolWeb#24]
Hey I have problem with the timeliner times.
The scan ends after few hours and the process stuck at 96% for even few days!!
I want to be able to stop the timeliner and see the results without the timeline.
It makes the scan not relevant if it done 3 days after the starting point..

Ido

**Comment by k1nd0ne** [comment]
Hello, 

Thank you for your experience feedback!

There is currently no built-in feature in VolWeb to disable the timeliner plugin in the engine. However, you can customize the engine to disable this task  (evidences/tasks.py) and build your own image of the volweb platform (using the dockerfile provided). I know it's not optimal... In any case as announced in the [discussions](https://github.com/k1nd0ne/VolWeb/discussions/23), VolWeb 3.0 development is taking the majority of my time right now. The Timeliner will be a dedicated task in VolWeb 3.0 which will enable the analyst to review the evidence while this task is running.


Best regards.

**Comment by Idodo6** [comment]
Hey 
Thanks for helping!
How can I do the editing part? What is circumstances of disabling the timeliner task?

**Comment by k1nd0ne** [comment]
Hello, 
The timeline generation is now performed in a dedicated task manually triggered in the Timliner menu.
Please check out the new release. 

Regards.
