### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by TaghikhaniAlireza** [k1nd0ne/VolWeb#8]
Hello,
I got some errors while trying to upload the ISF file. I got "CSRF verification failed. Request aborted." I have no idea what happened. I'll appreciate you help me. 
I run the "VolWeb-1.3.2-beta" version.
Thank you

**Comment by k1nd0ne** [comment]
Hi, 
Thank you for reaching out!

Could you please provide the logs of the standard output of docker when the error appears ? 

You can do it this way: 
```
cd VolWeb/docker
docker-compose down
docker-compose up > logs.txt
```
Trigger the error then: 
```
cd VolWeb/docker
docker-compose down
```

You can place the logfile in this issue or send it to me over at k1nd0ne@mail.com. 


Best regards.
